services:
  prod:
    build: .
    ports:
      - "10000:10000" 
    volumes:
      - "./:/srv/app:rw"
      - "./docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "./docker/ports.conf:/etc/apache2/ports.conf"
    command: bash -c "composer install --no-interaction --prefer-dist && apache2-foreground"